module.exports = {
  getBrandCodeUrl: '/api/v1/brand',
  fileUpLoadUrl: '/api/v1/upload',
  publishUrl: '/api/v1/release',
  getHomeListUrl: '/api/v1/release/list',
  getUserInfoUrl: '/api/v1/account',
  setFollowStateUrl: '/api/v1/follow/state',
  aduitUrl:'/api/v1/audit',
  buyMessageUrl: '/api/v1/buy_message',
  newsListUrl: '/api/v1/news/list',
  newsReadUrl: '/api/v1/news/red/{id}',
  buyListUrl: '/api/v1/buy_message/list',
  merchantUrl: '/api/v1/audit/info',
  UpUserInfoUrl:'/api/v1/account',
  fansUrl: '/api/v1/fans',
  followUrl: '/api/v1/follow',
  auditInfoUrl: '/api/v1/audit/info',
  openVipUrl: '/api/v1/account/vip',
  priceUrl:'/api/v1/account/vip/price',
  leaveUrl: 'api/v1/news'
};
